name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up tools
      uses: actions/setup-java@v1
      uses: actions/setup-node@v1
      with:
        java-version: '11.x'
        node-version: '10.x'
    - name: Build with Gradle
      run: ./gradlew build
