name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.3
    - name: Build with Gradle
      run: ./gradlew build
    - name: Release artifact
      uses: actions/upload-artifact@master
      with:
        name: data-as-a-board
        path: service/build/libs/data-as-a-board.jar
